# Generated by Django 6.0.2 on 2026-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, help_text='Wide banner looks best.', null=True, upload_to='collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('games', models.ManyToManyField(blank=True, related_name='collections', to='games.game')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
